config/routes.rb
Rails.application.routes.draw do
  resources :collections
  resources :items
  resources :users
  resources :categories

  resources :collect_proposals, except: %i[edit update] do
    member do
      post :accept
      post :reject
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[ show edit update destroy ]

  # GET /collections or /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1 or /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:item_id, :user_id, :collection_date)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<div id="<%= dom_id collection %>">
  <p>
    <strong>Item:</strong>
    <%= collection.item_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= collection.user_id %>
  </p>

  <p>
    <strong>Collection date:</strong>
    <%= collection.collection_date %>
  </p>

</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection) do |form| %>
  <% if collection.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item_id, style: "display: block" %>
    <%= form.text_field :item_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :collection_date, style: "display: block" %>
    <%= form.datetime_field :collection_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Show this collection", @collection %> |
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Collections</h1>

<div id="collections">
  <% @collections.each do |collection| %>
    <%= render collection %>
    <p>
      <%= link_to "Show this collection", collection %>
    </p>
  <% end %>
</div>

<%= link_to "New collection", new_collection_path %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @collection %>

<div>
  <%= link_to "Edit this collection", edit_collection_path(@collection) %> |
  <%= link_to "Back to collections", collections_path %>

  <%= button_to "Destroy this collection", @collection, method: :delete %>
</div>